spring:
  application:
    name: Trading Analytics

  datasource:
    url: jdbc:sqlite:${user.home}/myapp.db
    driver-class-name: org.sqlite.JDBC

    hikari:
      maximum-pool-size: 1
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: INFO
    com.example.ta: DEBUG

telegram:
  news:
    message-lifetime-hours: 3
    cleanup-interval: "0 */5 * * * ?" # Очистка каждый 5 минут
